### ISSUE TITLE
Design the logo

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [sputlytics/sputlytics.github.io#3]

**Comment by lnmunhoz** [comment]
![shot_1295412842](https://cloud.githubusercontent.com/assets/4376835/13755883/0b84578c-e9fc-11e5-87ce-c587ced35b7a.png)
![contact_1x](https://cloud.githubusercontent.com/assets/4376835/13755885/0c3d4058-e9fc-11e5-89ff-6e6f8200ccab.png)
![spinner-6](https://cloud.githubusercontent.com/assets/4376835/13755886/0d2535ac-e9fc-11e5-8119-6ece32b3089e.gif)
![sputnik_1_1x](https://cloud.githubusercontent.com/assets/4376835/13755889/0e29780a-e9fc-11e5-92d1-caacae499d16.jpg)

**Comment by lnmunhoz** [comment]
![sputnik](https://cloud.githubusercontent.com/assets/4376835/13755899/1f03b136-e9fc-11e5-9602-53d9b56932d7.png)
![punk_movie___sputnik_by_popbot1383-d5ppq7t](https://cloud.githubusercontent.com/assets/4376835/13755900/2147e200-e9fc-11e5-81ab-bd0a578d7f45.png)

**Comment by caio-ribeiro-pereira** [comment]
Take a look this simple logo I made into http://www.squarespace.com/logo

![sputlytics-logo](https://cloud.githubusercontent.com/assets/551228/13756517/fda4228e-e9fe-11e5-9a71-93d5393e63f5.png)

**Comment by caio-ribeiro-pereira** [comment]
![sputlytics-logo 1](https://cloud.githubusercontent.com/assets/551228/13756548/272d14ee-e9ff-11e5-8e87-e1cac4e38ce5.png)

**Comment by caio-ribeiro-pereira** [comment]
![sputlytics-logo 2](https://cloud.githubusercontent.com/assets/551228/13756564/412eca9a-e9ff-11e5-8b44-eb14a2b65954.png)
