### ISSUE TITLE
Screenshots not working

### ISSUE THREAD

**Issue by batjko** [sputlytics/sputlytics.github.io#5]
![image](https://cloud.githubusercontent.com/assets/7287076/14104657/2b762784-f59e-11e5-87b9-172d5286e649.png)

**Comment by caio-ribeiro-pereira** [comment]
cache, just force clear the cache :)

**Comment by batjko** [comment]
I've never been on your page before, so there wasn't any cache for this.
Still, I tried and still not getting there:
![image](https://cloud.githubusercontent.com/assets/7287076/14108561/e70b5a34-f5b5-11e5-9266-2510b49b7508.png)

**Comment by caio-ribeiro-pereira** [comment]
Sorry, I forgot to send the screenshots, I fixed right now.  

Thank you!  

Regards,
Caio Ribeiro Pereira
Developer, blogger and writter
About: http://crpwebdev.com
Blog: http://udgwebdev.com
